version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: my_rpm_app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: my_rpm_db
    ports:
      - "5432:5432" # Expose port 5432 for local development
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data even if the container is restarted

  my-rpm-app:
    build:
      context: ./my-rpm-app
    container_name: my_rpm_app_container
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://my_rpm_app:app@postgres:5432/my_rpm_db
    ports:
      - "8080:8080" # Map port 8080 for the application
    volumes:
      - ./my-rpm-app:/usr/src/app
    command: >
      sh -c "npm install && npm run dev"

volumes:
  postgres_data:
    driver: local

